version: '3.3'

services:
  address-api-database:
    image: postgres:11.2
    container_name: address-api-database
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=address-api
    ports:
      - 5434:5432
    volumes:
      - address-api-db-data:/var/lib/postgresql/data
    networks:
      - address-api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 5

  address-api-backend:
    container_name: address-api-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: address-api-backend:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - address-api-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#      - DB_HOST=address-api-database

volumes:
  address-api-db-data:
    driver: local

networks:
  address-api-network:
    driver: bridge