spring:
  profile: docker
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:address-api-database}:${DB_PORT:5432}/${DB_NAME:address-api}