spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:asdqwe123}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:address-api}
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:db/changelog-master.xml
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true

geolocation:
  apiKey: ${GEO_LOCATION_API_KEY}
